# name: 'terratest'

# on:
#   pull_request:
#     branches:
#       - master
#     paths-ignore:
#       - '**.md'

# env:
#   ARM_CLIENT_ID: ${{ secrets.AZURE_ARM_CLIENT_ID }}
#   ARM_CLIENT_SECRET: ${{ secrets.AZURE_ARM_CLIENT_SECRET }}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_ARM_SUBSCRIPTION_ID }}
#   ARM_TENANT_ID: ${{ secrets.AZURE_ARM_TENANT_ID }}

# jobs:
#   # Job that runs terratest and runs integration test on the infrastructure provisioned.
#   terratest:
#     name: terratest
#     runs-on:
#       'ubuntu-latest'
#     defaults:
#       run:
#         shell: bash
#         working-directory: test

#     steps:
#       # Checkout the repository to the GitHub Actions runner
#       - name: Checkout
#         uses: actions/checkout@v2

#       # Install the latest version of Terraform CLI
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       # Install and set up Golang
#       - name: Set Up Go
#         uses: actions/setup-go@v2

#       # Get all golang dependencies
#       - name: Get dependencies
#         run: |
#           go get -v -t -d ./...
#           if [ -f Gopkg.toml ]; then
#               curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#               dep ensure
#           fi
#       # Run terratest
#       - name: Run Terratest
#         run: go test -v -timeout 90m

